PREP(compileRunbacks);
PREP(getStorage);
PREP(loadVehicleTOC);
PREP(runCallback);
PREP(sanitizeStoragePrefix);
PREP(verifyConfig);
PREP(verifyConfigServer);
PREP(verifyConfigStorage);
PREP(xehVehicleInitPost);
