name = "Open Vehicle Garage"
author = "UnseenKill/gor3Splatter"
prefix = "a3ovg"
mainprefix = "z"

[files]
include = [
    "a3ovg-logo.paa",
    "LICENSE",
    "README.md",
    "mod.cpp"
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "1779063631", # ZEN
]

[hemtt.launch.ace3]
workshop = [
    "463939057", # ACE3
]

[hemtt.launch.inidbi2]
workshop = [
    "1768992669", # INIDBI2
]

[hemtt.launch.bwmod]
workshop = [
    "1200127537", # BwMOD
]

[hemtt.launch.stratis]
extends = "default"
mission = "a3ovg-stratis.Stratis"
