name = "Open Vehicle Garage"
author = "UnseenKill/gor3Splatter"
prefix = "a3ovg"
mainprefix = "z"

[files]
include = [
    "a3ovg-logo.paa",
    "LICENSE",
    "README.md",
    "mod.cpp"
]

[lints.stringtables.usage]
options.ignore = [
    # hemtt bug again
    "str_a3ovg_ui_vehiclegaragedeniedcrewed",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "1779063631", # ZEN
]

[hemtt.launch.inidbi2]
workshop = [
    "1768992669", # INIDBI2
]

[hemtt.launch.stratis]
extends = "default"
mission = "a3ovg-stratis.Stratis"
